### ISSUE TITLE
Retakers

### ISSUE THREAD

**Issue by florian-rabe** [florian-rabe/Teaching#7]
I'll announce the procedure for retakers in this issue.

I created this issue so that affected people can subscribe to it already.

**Comment by ruicao-github** [comment]
Dear Dr. florian-rabe,

I have seen the release of the first homework set for AaDS. Has the retake policy also settled?

Thank you

**Comment by florian-rabe** [comment]
I have settled it now.

Retakers are treated as other students with these exceptions:
* If I do an unannounced quiz in a slot in which you have a conflict, that quiz will not count towards your grade.
* If I do an announced quiz in a slot in which you have a conflict, you have to take it. It will take place at the beginning of the lecture and take about 20 minutes. It is understood if you miss that time in the other course.

**Comment by florian-rabe** [comment]
The first quiz will be on Thursday from 11:15 to 11:30.

**Comment by florian-rabe** [comment]
The second quiz will be on Tuesday at 9:45.

**Comment by ksali** [comment]
Hello,

Last time during lecture you mentioned that for the second part of the course, the quizzes and the exam will be mostly based on the material covered during lecture time. I was wondering how would this work for retakers that can't attend class.

Best regards,
Kejsi Sali

**Comment by florian-rabe** [comment]
Usually the quiz material will be in the notes in one way or another.

But it may become harder to judge the relative importance of the sections when only reading the notes because we're going through the material faster now.

Retakers will probably be fine because they have some experience already.

I mostly meant it as a heads-up for first-year students.

**Comment by ShabbarRazaPk94** [comment]
Hi, will there be a quiz this Thursday(30/03/2017)?

**Comment by gcakir** [comment]
@ShabbarRazaPk94, most probably because we did not have a quiz last week.

**Comment by ruicao-github** [comment]
The instructor said that he will anounce in this thread when there is a quiz that requires the retaker to attend. Since he has not announced anything in this thread yet. I don't think there will be a quiz.

**Comment by florian-rabe** [comment]
Yes, there will be a quiz tomorrow.

**Comment by ShabbarRazaPk94** [comment]
I really like the content of this course and appreciate all efforts by the instructor. The way this course is being administered is however not convenient for students.

It would be great if we could have a fixed plan for quizzes for the entire semester, or if they have to be announced every time, it would be more reasonable to have the announcements at least two days before the time of the quiz (some students might suggest more time in this regard).

There were only two quizzes announced in this issue, and apparently there were three quizzes in the class so far. If the attendance is not mandatory, then the idea of unannounced quizzes does not seem to be fair.

There is no policy for makeups for students who may not be able to make it to a quiz due to illness or if at the time of the quiz they have classes that may have mandatory attendance. It would only be fair to have a policy addressing these issues.

**Comment by florian-rabe** [comment]
@ShabbarRazaPk94 I understand the sentiment.

The overall quiz schedule is essentially determined by the calendar: there is a quiz every 3-4 lectures.

Note that you are generally expected to attend every lecture of course you register for.
Some students prefer to organize their time differently or to retake a course.
That is fine that, but it becomes the student's responsibility to find out what material was discussed in the lecture.
For example, in this case, I announced the quiz in the lecture on Tuesday.

**Comment by florian-rabe** [comment]
See https://github.com/florian-rabe/Teaching/issues/104 for the remaining 2 quizzes.
